# The URL the site will be built for
base_url = "https://rohow.de"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Default language
default_language = "en"

[languages.de]
title = "RoHOW – Robotic Hamburg Open Workshop"

[languages.en]
title = "RoHOW – Robotic Hamburg Open Workshop"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
menu_items = [
    { name = "RoHOW", url = "/" },
    { name = "Teams", url = "/teams" },
    { name = "Schedule", url = "/schedule" },
    { name = "Venue", url = "/venue" },
    { name = "Press", url = "/press" },
    { name = "Contact", url = "/contact" },
]
