# The URL the site will be built for
base_url = "https://oleflb.github.io/rohow.github.io/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

title = "RoHOW - Robotic Hamburg Open Workshop"

[markdown]
highlight_code = true

[extra]
menu_items = [
    { name = "RoHOW", url = "/" },
    { name = "Teams", url = "/teams" },
    { name = "Schedule", url = "/schedule" },
    { name = "Venue", url = "/venue" },
    { name = "Press", url = "/press" },
    { name = "Contact", url = "/contact" },
]
footer_links = [
    { name = "Imprint", url = "/imprint" },
    { name = "Privacy Policy", url = "/privacy-policy" },
]
